### ISSUE TITLE
Update song db halts if target folder is from NTFS and having a long named file (linux)

### ISSUE THREAD

**Issue by yaasdf** [exch-bms2/beatoraja#164]
Reproduced with:
Sky of the day of summer (BOF2013)
Sacred Moon(Radio Edit) (G2R2014)
Lostwork (A-1 Climax 5th)
All of the BMS above have a readme file with dramastic long filename. Copying these BMS to ext4 partition would reject these readme files and the update process proceeds.

OS: Manjaro Linux x64
Version: beatoraja 0.5.3

Log:
二月 06, 2018 10:41:56 上午 bms.player.beatoraja.song.SQLiteSongDatabaseAccessor$SongDatabaseUpdater updateSongDatas
严重: 楽曲データベース更新時の例外:java.nio.file.FileSystemException: /mnt/E/bms/Event/BOF2014_G2R2014/Girls forM教/Sacred Moon(Radio Edit): No such file or directory
java.nio.file.DirectoryIteratorException: java.nio.file.FileSystemException: /mnt/E/bms/Event/BOF2014_G2R2014/Girls forM教/Sacred Moon(Radio Edit): No such file or directory
	at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:172)
	at sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:201)
	at bms.player.beatoraja.song.SQLiteSongDatabaseAccessor$SongDatabaseUpdater.processDirectory(Unknown Source)
	at bms.player.beatoraja.song.SQLiteSongDatabaseAccessor$SongDatabaseUpdater.processDirectory(Unknown Source)
	at bms.player.beatoraja.song.SQLiteSongDatabaseAccessor$SongDatabaseUpdater.processDirectory(Unknown Source)
	at bms.player.beatoraja.song.SQLiteSongDatabaseAccessor$SongDatabaseUpdater.updateSongDatas(Unknown Source)
	at bms.player.beatoraja.song.SQLiteSongDatabaseAccessor.updateSongDatas(Unknown Source)
	at bms.player.beatoraja.launcher.PlayConfigurationView.loadBMS(Unknown Source)
	at bms.player.beatoraja.launcher.PlayConfigurationView.loadAllBMS(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
...

**Comment by parataxia** [comment]
Had the same issue with the same song in fact, ended up moving it elsewhere until this is fixed. I think java's file I/O doesn't like NTFS (or ntfs-3g) potentially.

**Comment by marysiamzawka** [comment]
I've stumbled upon the same issue on Arch Linux
At first I thought it's related to long paths leading to my BMS directory, so I set up a short symlink - no dice.
Then I looked at the exact folder in which the scanner gave up, and found a text file with a very long name `エレプロってBMS界隈から見ればチョット頭湧いてる奴らが集まってる「レーベル」って思われてるんだろうなぁ・・・・。あっ、ちなみに僕らはあくまで「創作サークル」って思ってますのでその辺よしなに頭の隅へと置いといて（ｒｙ.txt`.
Deleting it fixed the issue.

Here I want to point out that I haven't had this issue either on Windows, or on Pop!_OS (which is Ubuntu-based), so it looks like it's an Arch-exclusive issue.
