### ISSUE TITLE
IIDX Premium Controller connection lost?

### ISSUE THREAD

**Issue by SackMagiclight** [exch-bms2/beatoraja#265]
* IIDX プレミアムコントローラーがbeatoraja利用中に操作不能になる現象です。
* beatoraja側の問題か、コントローラー側(OS側)の問題かは現状判別できていません。
* 操作不能時と通常時のUSBキャプチャを添付します→[error.zip](https://github.com/exch-bms2/beatoraja/files/1847690/error.zip)
  * [wireshark](https://www.wireshark.org/) を利用しました
  * error.pcapng : エラー時、noerror.pcapng : 通常時です

**Comment by SackMagiclight** [comment]
SHA-1: d24ca345eba0c6ff640ef49b2f9e7a34c37c44f9

でプレイしていたところ、下記ヌルポが出ていました。
もしかしたらこの周りかもしれませんが、他のコントローラーで切れる不具合が挙がっていないので違う可能性が高そうです（？）

```
java.lang.NullPointerException
	at bms.player.beatoraja.audio.GdxSoundDriver.stop(GdxSoundDriver.java:158)
	at bms.player.beatoraja.audio.GdxSoundDriver.stop(GdxSoundDriver.java:1)
	at bms.player.beatoraja.audio.AbstractAudioDriver.play0(AbstractAudioDriver.java:328)
	at bms.player.beatoraja.audio.AbstractAudioDriver.play(AbstractAudioDriver.java:305)
	at bms.player.beatoraja.play.JudgeManager.update(JudgeManager.java:491)
	at bms.player.beatoraja.play.KeyInputProccessor$JudgeThread.run(KeyInputProccessor.java:188)
```

**Comment by SackMagiclight** [comment]
beatorajaプレイ中に**他ウィンドウにアクティブが取られる**おま環のような挙動が濃厚なので一旦Closeします。
