### ISSUE TITLE
[Mocha] FFmpeg playback error

### ISSUE THREAD

**Issue by excln** [exch-bms2/beatoraja#354]
動画BGAを含むBMSを再生すると、動画開始時に下記の例外が発生して落ちることがあります。あるいは例外は発生しないが動画が再生されないこともあります。

```
...
情報: STATE_PLAYに移行
Exception in thread "LWJGL Application" java.lang.IllegalStateException: Deque full
        at java.util.concurrent.LinkedBlockingDeque.addLast(Unknown Source)
        at bms.player.beatoraja.play.bga.FFmpegProcessor$MovieSeekThread.exec(Unknown Source)
        at bms.player.beatoraja.play.bga.FFmpegProcessor.play(Unknown Source)
        at bms.player.beatoraja.play.bga.BGAProcessor.getBGAData(Unknown Source)
        at bms.player.beatoraja.play.bga.BGAProcessor.drawBGA(Unknown Source)
        at bms.player.beatoraja.play.SkinBGA.draw(Unknown Source)
        at bms.player.beatoraja.skin.Skin.drawAllObjects(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

この問題はMocha版（少なくとも0.6.1と0.6.2の両方）でのみ発生を確認できているので、ライブラリのバージョンに依存していると思われます。また、実行環境によっても挙動が変わる可能性があります。

本質的な解決にはなっていないと思われますが、とりあえず deque への追加が失敗しても例外が発生しないようにして落ちるのを防ぐPRを作成します。

**Comment by exch-bms2** [comment]
JavaCVのバージョンが1.4.2 -> 1.4.4に変わっておいるためissueを一旦closeします。
