### ISSUE TITLE
[Mocha-0.6.2] BMSON load error

### ISSUE THREAD

**Issue by excln** [exch-bms2/beatoraja#356]
Mocha版 0.6.2 にて、特定のBMSON曲を選択すると高確率で例外が発生して落ちるようです。0.6.1以前およびMocha版以外では発生しません。 jbms-parser.jar の更新部分に問題がありそうです。

```
情報: 描画されないことが確定しているSkinObject削除 : 0 / 119
Exception in thread "Thread-193" java.lang.NullPointerException
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.player.beatoraja.PlayerResource.loadBMSModel(Unknown Source)
        at bms.player.beatoraja.select.MusicSelector.lambda$render$1(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-196" java.lang.NullPointerException
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.player.beatoraja.PlayerResource.loadBMSModel(Unknown Source)
        at bms.player.beatoraja.select.MusicSelector.lambda$render$1(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-197" java.lang.NullPointerException
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.player.beatoraja.PlayerResource.loadBMSModel(Unknown Source)
        at bms.player.beatoraja.select.MusicSelector.lambda$render$1(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-198" java.lang.NullPointerException
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.player.beatoraja.PlayerResource.loadBMSModel(Unknown Source)
        at bms.player.beatoraja.select.MusicSelector.lambda$render$1(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.model.BMSONDecoder.decode(Unknown Source)
        at bms.player.beatoraja.PlayerResource.loadBMSModel(Unknown Source)
        at bms.player.beatoraja.PlayerResource.setBMSFile(Unknown Source)
        at bms.player.beatoraja.select.MusicSelector.render(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

↑の例外のうち、最後以外は選曲バー移動時の読み込みで発生しているものっぽいです（原因はおそらく同じですが）

エラーが発生するBMSONの例：[🎹5 エンバディメント ～2010 flynation mix～ [24KEYS] ](http://sky.geocities.jp/exclusion_bms/table24k/table.html)

十分な数が検証できていませんが、24鍵、48鍵モードのみの可能性があります。（24鍵でも正常に読み込めるものもあります）

**Comment by exch-bms2** [comment]
layer_eventsの拡張機能実装時に不備がありました。次回のバージョンで修正されます。
