### ISSUE TITLE
[Mocha-0.6.5] Error in music selection

### ISSUE THREAD

**Issue by excln** [exch-bms2/beatoraja#388]
### エラー発生条件

* Mocha版 0.6.5
* デフォルト選曲スキン使用
* 「現在のモードのプレイ履歴がない末端の曲フォルダ」を選択すると必ず下記のエラーが発生
  * 添字の `3` は確かLNモードによって変わっていたと思います

```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 3
        at bms.player.beatoraja.select.BarRenderer.render(Unknown Source)
        at bms.player.beatoraja.select.SkinBar.draw(Unknown Source)
        at bms.player.beatoraja.skin.Skin.drawAllObjects(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

### 備考

GitHub版では発生しません。スキンファイルはGitHub版とMocha版で若干の差異があるようですが、原因は本体側のようです。また、LITONEスキン（少し古いバージョンですが）では発生しませんでした。

**Comment by exch-bms2** [comment]
7c92c22b1fac0640d9d1209c484be5b354ba3c16 で修正済みです。
これに限らず、配列を直接触れるメソッドは極力削除していきたいですね。
