### ISSUE TITLE
Out of memory error occurs when playing BMSON on portaudio

### ISSUE THREAD

**Issue by SackMagiclight** [exch-bms2/beatoraja#395]
reopen #216 

BMSONをportaudioを利用してロードした場合、ファイルスライシングに失敗します。
bmson ex) http://manbow.nothing.sh/event/event.cgi?action=More_def&num=359&event=123

OpenALの場合は正常に動作します。

SHA-1: 6577ef1644ae1c31491fa10b23fdaaae19c10e00

OS:windows 10 Home
CPU: i7-7700HQ
RAM: 16GB
GPU: GTX1050
Audio Device: Realtek High Definition Audio

![image](https://user-images.githubusercontent.com/20876249/50370850-8a79b500-05f1-11e9-945b-2b291e94081b.png)

<details>
<summary>スタックトレース</summary>
<pre>
<code>
警告: 音源(wav)ファイルスライシング失敗。Direct buffer memory [土 12 22 13:59:16 JST 2018]
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:694)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at bms.player.beatoraja.audio.PCM.getDirectByteBuffer(PCM.java:158)
	at bms.player.beatoraja.audio.ShortDirectPCM.getSample(ShortDirectPCM.java:89)
	at bms.player.beatoraja.audio.ShortDirectPCM.changeSampleRate(ShortDirectPCM.java:68)
	at bms.player.beatoraja.audio.ShortDirectPCM.changeSampleRate(ShortDirectPCM.java:1)
	at bms.player.beatoraja.audio.PortAudioDriver.getKeySound(PortAudioDriver.java:106)
	at bms.player.beatoraja.audio.PortAudioDriver.getKeySound(PortAudioDriver.java:1)
	at bms.player.beatoraja.audio.AbstractAudioDriver$AudioCache.load(AbstractAudioDriver.java:474)
	at bms.player.beatoraja.audio.AbstractAudioDriver$AudioCache.load(AbstractAudioDriver.java:1)
	at bms.player.beatoraja.ResourcePool.get(ResourcePool.java:50)
	at bms.player.beatoraja.audio.AbstractAudioDriver.setModel(AbstractAudioDriver.java:260)
	at bms.player.beatoraja.BMSResource$AudioLoaderThread.run(BMSResource.java:232)
警告: 音源(wav)ファイルスライシング失敗。Direct buffer memory [土 12 22 13:59:17 JST 2018]
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:694)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at bms.player.beatoraja.audio.PCM.getDirectByteBuffer(PCM.java:158)
	at bms.player.beatoraja.audio.ShortDirectPCM.getSample(ShortDirectPCM.java:89)
	at bms.player.beatoraja.audio.ShortDirectPCM.changeSampleRate(ShortDirectPCM.java:68)
	at bms.player.beatoraja.audio.ShortDirectPCM.changeSampleRate(ShortDirectPCM.java:1)
	at bms.player.beatoraja.audio.PortAudioDriver.getKeySound(PortAudioDriver.java:106)
	at bms.player.beatoraja.audio.PortAudioDriver.getKeySound(PortAudioDriver.java:1)
	at bms.player.beatoraja.audio.AbstractAudioDriver$AudioCache.load(AbstractAudioDriver.java:474)
	at bms.player.beatoraja.audio.AbstractAudioDriver$AudioCache.load(AbstractAudioDriver.java:1)
	at bms.player.beatoraja.ResourcePool.get(ResourcePool.java:50)
	at bms.player.beatoraja.audio.AbstractAudioDriver.setModel(AbstractAudioDriver.java:260)
	at bms.player.beatoraja.BMSResource$AudioLoaderThread.run(BMSResource.java:232)
警告: 音源(wav)ファイルスライシング失敗。Direct buffer memory [土 12 22 13:59:18 JST 2018]
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:694)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at bms.player.beatoraja.audio.PCM.getDirectByteBuffer(PCM.java:158)
	at bms.player.beatoraja.audio.ShortDirectPCM.getSample(ShortDirectPCM.java:89)
	at bms.player.beatoraja.audio.ShortDirectPCM.changeSampleRate(ShortDirectPCM.java:68)
	at bms.player.beatoraja.audio.ShortDirectPCM.changeSampleRate(ShortDirectPCM.java:1)
	at bms.player.beatoraja.audio.PortAudioDriver.getKeySound(PortAudioDriver.java:106)
	at bms.player.beatoraja.audio.PortAudioDriver.getKeySound(PortAudioDriver.java:1)
	at bms.player.beatoraja.audio.AbstractAudioDriver$AudioCache.load(AbstractAudioDriver.java:474)
	at bms.player.beatoraja.audio.AbstractAudioDriver$AudioCache.load(AbstractAudioDriver.java:1)
	at bms.player.beatoraja.ResourcePool.get(ResourcePool.java:50)
	at bms.player.beatoraja.audio.AbstractAudioDriver.setModel(AbstractAudioDriver.java:260)
	at bms.player.beatoraja.BMSResource$AudioLoaderThread.run(BMSResource.java:232)
java.io.IOException: D:\Git\beatoraja\songs\G2R2018\overground\猫箱喫茶店 -neko baco cafe-\[BACO]LastVoyager\lead56.ogg : can't convert to PCM
	at bms.player.beatoraja.audio.PCM$PCMLoader.loadPCM(PCM.java:324)
	at bms.player.beatoraja.audio.PCM.load(PCM.java:66)
	at bms.player.beatoraja.audio.PCM.load(PCM.java:102)
	at bms.player.beatoraja.audio.AbstractAudioDriver$AudioCache.load(AbstractAudioDriver.java:467)
	at bms.player.beatoraja.audio.AbstractAudioDriver$AudioCache.load(AbstractAudioDriver.java:1)
	at bms.player.beatoraja.ResourcePool.get(ResourcePool.java:50)
	at bms.player.beatoraja.audio.AbstractAudioDriver.setModel(AbstractAudioDriver.java:260)
	at bms.player.beatoraja.BMSResource$AudioLoaderThread.run(BMSResource.java:232)
</code>
</pre>
</details>

***

おそらくどこかのメモリ解放忘れでしょうか？
port audio  <--->  OpenAL
![image](https://user-images.githubusercontent.com/20876249/50371373-e0078f00-05fc-11e9-8214-a7cd227f370b.png)

**Comment by SackMagiclight** [comment]
* デスクトップ(WIn10 pro + 2700X + RTX2080)
  * [Essence STX](https://www.asus.com/jp/Essence-Hi-Fi-Audio/Xonar_Essence_STX/)
    * ASIO : OK
    * Audio Device（デフォルト スピーカー出力）: OK
  * Nvidia high definition audio
    * ディスプレイオーディオ : NG
  * OpenAL : OK
* [ノートPC](https://github.com/exch-bms2/beatoraja/issues/395#issue-393643749)
  * Realtek High Definition Audio : NG
  * OpenAL OK

> 低スペック対応の一環として取り組んでいく

とのお話を聞いていますので、一旦置いておきます。
