### ISSUE TITLE
When I execute jar with a non-existing BMS path, the application receives no keyboard inputs

### ISSUE THREAD

**Issue by yuinore** [exch-bms2/beatoraja#42]
What happens:
Immediately after the game window appear, the game window disappears.
After that, the console window receives no keyboard input.
I built the source code and ran the application,
but the same thing has happened with Released version 0.4.1.

Expected behavior:
The application exits immediately, and returns to cmd.exe

Reproduce step:
execute beatoraja.jar with a non-existing BMS path.
(for example: `java -jar beatoraja.jar C:\non-existing-file` )

Console output:

```
Controllers: added manager for application, 1 managers active

5 27, 2017 2:25:00 午後 bms.model.BMSDecoder decode
重大: BMSファイル解析中の例外 : java.nio.file.NoSuchFileException - C:\non-existing-file
5 27, 2017 2:25:00 午後 bms.player.beatoraja.PlayerResource setBMSFile
警告: 楽曲が存在しないか、解析時にエラーが発生しました:C:\non-existing-file
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at bms.player.beatoraja.play.BMSPlayer.<init>(Unknown Source)
        at bms.player.beatoraja.MainController.changeState(Unknown Source)
        at bms.player.beatoraja.MainController.create(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

Environment:
- Windows 10 64bit
- JRE 1.8.0_131
- Apache Ant 1.10.1

**Comment by yuinore** [comment]
issueを立てました。

**Comment by yuinore** [comment]
Thank you 😊
