### ISSUE TITLE
Configuration window shows up blank

### ISSUE THREAD

**Issue by KarenKonou** [exch-bms2/beatoraja#434]
The configuration window shows blank and log displays the following error

OS: Arch Linux 64-bit with openJDK 8

![Screenshot_2019-04-17_21-30-54](https://user-images.githubusercontent.com/37159053/56315495-1e026300-6158-11e9-83e8-859e6922b2f1.png)

```
Apr 17, 2019 9:28:54 PM bms.player.beatoraja.launcher.PlayConfigurationView initialize
INFO: 初期化時間(ms) : 3
Apr 17, 2019 9:28:55 PM bms.player.beatoraja.MainLoader start
INFO: 初期化時間(ms) : 2084
java.lang.ArrayIndexOutOfBoundsException: -22
        at com.sun.prism.impl.GlyphCache.getCachedGlyph(GlyphCache.java:332)
        at com.sun.prism.impl.GlyphCache.render(GlyphCache.java:147)
        at com.sun.prism.impl.ps.BaseShaderGraphics.drawString(BaseShaderGraphics.java:2101)
        at com.sun.javafx.sg.prism.NGText.renderText(NGText.java:312)
        at com.sun.javafx.sg.prism.NGText.renderContent2D(NGText.java:270)
        at com.sun.javafx.sg.prism.NGShape.renderContent(NGShape.java:261)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
        at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)
        at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by SackMagiclight** [comment]
Is openjfx installed?

**Comment by KarenKonou** [comment]
Yes
![image](https://user-images.githubusercontent.com/37159053/56354587-6fe8ce80-61d4-11e9-8b51-7dd0ee0c9413.png)
