### ISSUE TITLE
Beatoraja crashes when loading songs

### ISSUE THREAD

**Issue by yantaisa11** [exch-bms2/beatoraja#437]
If a song is loaded on the play screen, it will crash.
プレイ画面で曲をロードするとbeatorajaが落ちてしまいます。
Version used 0.6.9
[log.txt](https://github.com/exch-bms2/beatoraja/files/3116705/log.txt)

**Comment by yanyaisa11** [comment]
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at bms.player.beatoraja.play.bga.BGAProcessor.prepare(Unknown Source)
        at bms.player.beatoraja.play.BMSPlayer.render(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
↑
問題と思われる個所

0.68にダウングレードしたところ正常にプレイできましたので0.69に問題があると思います。
(I downgraded to 0.68 and I can play normally, so I think there is a problem with 0.69)
