### ISSUE TITLE
[MacOS] [0.7.4] black game window after launching beatoraja

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#462]
**Issue description:**
After clicking "Play" button in launcher window a beatoraja opens with black screen. It seems 
Game window does not respond to any input. Tried to load BGM to test if I can hear audio but I can not.

**to reproduce:**
1. open beatoraja.jar or beatoraja-config.command
2. press "Play" button

 <details>
<summary><ins>System Specifications:</ins></summary>

```
Computer: MacBook Pro (17-inch, Mid 2010) 
CPU: 2,66 GHz Intel Core i7 
GPU: NVIDIA GeForce GT 330M 512 MB / Intel HD Graphics 288 MB 
RAM: 8 GB 1067 MHz DDR3 
Internal storage: SSD Samsung Pro 480GB
 OS: 10.13.6 OS X El Capitan 
Native Resolution: 1920x1200
 Game Resolution: 1280x720
```
</details>
 
<details>
<summary><ins>Console Log:</ins></summary>

```
Last login: Tue Nov 26 16:53:57 on ttys000
mac:~ macbook$ /Applications/Games/beatoraja0.7.4/beatoraja-config.command ; exit;
Picked up _JAVA_OPTIONS: -Dsun.java2d.opengl=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Nov 26, 2019 4:54:07 PM bms.player.beatoraja.launcher.PlayConfigurationView initialize
INFO: 初期化時間(ms) : 5
Nov 26, 2019 4:55:12 PM bms.player.beatoraja.MainController$SystemSoundManager <init>
INFO: 検出されたBGM Set : 0 Sound Set : 0
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Error creating controller manager: com.badlogic.gdx.controllers.desktop.DesktopControllerManager
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:120)
	at com.badlogic.gdx.controllers.Controllers.getControllers(Controllers.java:51)
	at bms.player.beatoraja.input.BMSPlayerInputProcessor.<init>(Unknown Source)
	at bms.player.beatoraja.MainController.create(Unknown Source)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:151)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx-controllers-desktop64.dylib' for target: Mac OS X, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:125)
	at com.badlogic.gdx.controllers.desktop.DesktopControllerManager.<init>(DesktopControllerManager.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.badlogic.gdx.utils.reflect.ClassReflection.newInstance(ClassReflection.java:93)
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:118)
	... 5 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: /private/var/folders/44/ggp6jwdj44d9bppp2dyfjtqh0000gn/T/libgdxmacbook/3d4752a8/libgdx-controllers-desktop64.dylib: dlopen(/private/var/folders/44/ggp6jwdj44d9bppp2dyfjtqh0000gn/T/libgdxmacbook/3d4752a8/libgdx-controllers-desktop64.dylib, 1): Symbol not found: __objc_empty_cache
  Referenced from: /private/var/folders/44/ggp6jwdj44d9bppp2dyfjtqh0000gn/T/libgdxmacbook/3d4752a8/libgdx-controllers-desktop64.dylib
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 in /private/var/folders/44/ggp6jwdj44d9bppp2dyfjtqh0000gn/T/libgdxmacbook/3d4752a8/libgdx-controllers-desktop64.dylib
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:321)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:121)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/44/ggp6jwdj44d9bppp2dyfjtqh0000gn/T/libgdxmacbook/3d4752a8/libgdx-controllers-desktop64.dylib: dlopen(/private/var/folders/44/ggp6jwdj44d9bppp2dyfjtqh0000gn/T/libgdxmacbook/3d4752a8/libgdx-controllers-desktop64.dylib, 1): Symbol not found: __objc_empty_cache
  Referenced from: /private/var/folders/44/ggp6jwdj44d9bppp2dyfjtqh0000gn/T/libgdxmacbook/3d4752a8/libgdx-controllers-desktop64.dylib
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 in /private/var/folders/44/ggp6jwdj44d9bppp2dyfjtqh0000gn/T/libgdxmacbook/3d4752a8/libgdx-controllers-desktop64.dylib
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:327)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:296)
	... 14 more
```
 </details>

**Comment by axion014** [comment]
この症状に遭遇しました。
libGDXのバージョンが問題のようなのですが現在使われているのがNightlyで
`jar -uf beatoraja.jar [https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-controllers-platform/1.9.8/gdx-controllers-platform-1.9.8-natives-desktop.jar]`
で直りました。

**Comment by Agrrox** [comment]
Closed. Problem not occurring in 0.7.5
