### ISSUE TITLE
Crash when entering key configuration screen

### ISSUE THREAD

**Issue by yantaisa11** [exch-bms2/beatoraja#486]
選曲画面で6キー押してキーコンフィグ画面に入ろうとするとゲームが落ちてしまいます
cmd.exeに下記のエラーメッセージが出てきました

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Error parsing JSON on line 2 near: al t = require("keyconfigmain")
*ERROR*if skin_config then
        return t.main()
else
        return t.header
end

        at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:550)
        at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:56)
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:729)
        at bms.player.beatoraja.skin.json.JSONSkinLoader.loadHeader(Unknown Source)
        at bms.player.beatoraja.skin.json.JSONSkinLoader.load(Unknown Source)
        at bms.player.beatoraja.skin.json.JSONSkinLoader.loadSkin(Unknown Source)
        at bms.player.beatoraja.skin.SkinLoader.load(Unknown Source)
        at bms.player.beatoraja.MainState.loadSkin(Unknown Source)
        at bms.player.beatoraja.config.KeyConfiguration.create(Unknown Source)
        at bms.player.beatoraja.MainController.changeState(Unknown Source)
        at bms.player.beatoraja.select.MusicSelector.input(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:233)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)

**Comment by doneara** [comment]
スキン種類:SKIN SELECTでスキンを設定しないと落ちてしまうようです。

**Comment by yantaisa11** [comment]
スキン選択画面からキーコンフィグ欄のスキンを選んだらキーコンフィグができるようになりましたが、新規でbeatorajaを利用するユーザーにとっては混乱を招きかねないのでデフォルトであらかじめ選択済みにしておくべきかと思います。

**Comment by doneara** [comment]
この問題は既存ユーザーのみ起きます。
原因はキーコンフィグのjsonスキンがなくなってluaスキンのみになったので既存ユーザーはjsonスキンを参照しているのでスキン部分が空白になってしまっています。

**Comment by doneara** [comment]
直りました。
https://github.com/exch-bms2/beatoraja/commit/59e29ad8daf9247d2e268524532a0af6c216508c
