### ISSUE TITLE
[0.7.7] LWJGL exception in music select.

### ISSUE THREAD

**Issue by mak1non** [exch-bms2/beatoraja#534]
Music select crash when scrolling specific song.  
I'm launching beatoraja with UTF-8 (`-Dfile.encoding="UTF-8"`), but this can reproduce without `-Dfile.encoding="UTF-8"`.

選曲画面をスクロールしている際に、特定の曲にカーソルが合うとbeatorajaがクラッシュします。   
私はbeatorajaをUTF-8で起動していますが、標準設定でも同じタイミングでクラッシュします。  

- Windows 10 Home (1909, 64bit)
- OpenJDK 14.0.1
(Java8でも発生自体は確認しています)
- JavaFX 14.0.1  
(`--module-path C:\apps\javafx-sdk-14.0.1\lib --add-modules=javafx.controls,javafx.fxml`)
- beatoraja 0.7.7 (Mocha-Repository)
- [DarkTheme](https://github.com/Shimi9999/DarkTheme)@`7445b1aff2498dbfee5ebd6264ce1e8b8d3fdd6c`
- https://www.youtube.com/watch?v=PwVBArq81uI

環境依存の可能性がありそうですが、もし本体側で対処可能であれば修正していただきたいです。何か必要な情報があれば遠慮なく言って頂けると助かります。

log:
```
C:\beatoraja>java -Dfile.encoding="UTF-8" -Xms1g -Xmx4g --module-path C:\apps\javafx-sdk-14.0.1\lib --add-modules=javafx.controls,javafx.fxml -cp beatoraja.jar;ir/* bms.player.beatoraja.MainLoader
Picked up _JAVA_OPTIONS: '-Dsun.java2d.opengl=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
5月 24, 2020 11:48:14 午前 bms.player.beatoraja.launcher.PlayConfigurationView initialize
情報: 初期化時間(ms) : 3
---- JPortAudio version 1246720, PortAudio V19.6.0-devel, revision unknown
5月 24, 2020 11:48:28 午前 bms.player.beatoraja.MainController$SystemSoundManager <init>
情報: 検出されたBGM Set : 0 Sound Set : 0
[Controllers] added manager for application, 1 managers active
5月 24, 2020 11:48:35 午前 bms.player.beatoraja.MainController$SystemSoundManager shuffle
情報: BGM Set : null Sound Set : null
5月 24, 2020 11:48:35 午前 bms.player.beatoraja.external.BMSSearchAccessor read
重大: BMS Search更新中の例外:Field not found: id (bms.player.beatoraja.external.BMSSearchAccessor$Fumen)
Serialization trace:
[][0].fumen[0].id
fumen (bms.player.beatoraja.external.BMSSearchAccessor$BMSSearchElement)
5月 24, 2020 11:48:36 午前 bms.player.beatoraja.skin.Skin prepare
情報: 描画されないことが確定しているSkinObject削除 : 1 / 245
5月 24, 2020 11:48:36 午前 bms.player.beatoraja.MainController create
情報: 初期化時間(ms) : 7731
5月 24, 2020 11:48:41 午前 bms.player.beatoraja.PixmapResourcePool loadPicture
警告: BGAファイル読み込み失敗。Couldn't load file: D:/bms/[NiGHTS．] Zero Dimension/_title.bmp
5月 24, 2020 11:48:41 午前 bms.player.beatoraja.PixmapResourcePool loadPicture
警告: BGAファイル読み込み再試行:D:\bms\[NiGHTS．] Zero Dimension\_title.bmp
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Unable to create a font with no texture regions.
        at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:163)
        at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:151)
        at bms.player.beatoraja.skin.SkinTextFont.prepareText(Unknown Source)
        at bms.player.beatoraja.skin.SkinText.setText(Unknown Source)
        at bms.player.beatoraja.skin.SkinText.draw(Unknown Source)
        at bms.player.beatoraja.skin.Skin.drawAllObjects(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:233)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

**Comment by Shimi9999** [comment]
選曲スキンにDarkThemeを使用し、`▼2 トココ21 [2.1]`にカーソルを合わせると再現しました。
ジャンル名の`㌍㌢`をDarkThemeで使用している[Koruri](https://github.com/Koruri/Koruri/tree/Koruri-20180915)フォントで表示しようとするとクラッシュするようです。
