### ISSUE TITLE
Stops working when a specific chart is selected in Music Select.

### ISSUE THREAD

**Issue by Fezike** [exch-bms2/beatoraja#538]
選曲画面で特定の譜面（Zerstidol -7Keys Another-やYJC Ultrastyle☆12など）を選択した際に確定で動作が停止する。
Modern ChicやLITONE6等のビットマップフォントを利用するスキンであれば回避できる（これらのスキンでもビットマップフォントを使用しなければ落ちる）。
以下動作停止の際にコマンドプロンプトに表示されたメッセージ。

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Unable to create a font with no texture regions.
        at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:163)
        at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:151)
        at bms.player.beatoraja.skin.SkinTextFont.prepareText(Unknown Source)
        at bms.player.beatoraja.skin.SkinText.setText(Unknown Source)
        at bms.player.beatoraja.skin.SkinText.draw(Unknown Source)
        at bms.player.beatoraja.skin.Skin.drawAllObjects(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:233)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)

**Comment by exch-bms2** [comment]
#534にて既に解決済
