### ISSUE TITLE
拡張BMP指定が多すぎると読み込みできない件について

### ISSUE THREAD

**Issue by listandtag** [exch-bms2/beatoraja#549]
https://www.dropbox.com/s/4bcnkpclzna93au/%5Borangentle%20X%20cyclia%5D%20THANATOS.rar?dl=0

この曲の「thanatos_6yk.pms」譜面が読み込みできません。
テストは 0.7.9, 0.7.8, 0.7.6 でフリーズを確認しました。0.7.2では読み込みできるとの報告もあります。

問題の譜面は510枚のBMPファイルを指定しています。
色々試してみたあげく、384枚までBMPファイルの指定を吹き飛ばしたら読み込みに成功しました。

他にBMP指定の多いBMSがあると思いますが、まだ他の曲はテストしてません。
修正よろしくお願いします。

**Comment by SackMagiclight** [comment]
```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: Index 1121 out of bounds for length 1000
        at bms.player.beatoraja.play.bga.BGImageProcessor.prepare(Unknown Source)
        at bms.player.beatoraja.play.bga.BGAProcessor.prepare(Unknown Source)
        at bms.player.beatoraja.play.BMSPlayer.render(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:233)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

**Comment by SackMagiclight** [comment]
@exch-bms2 
原因はここ臭いですが、単純に上げるだけというのも悩ましいですね

https://github.com/exch-bms2/beatoraja/blob/master/src/bms/player/beatoraja/play/bga/BGImageProcessor.java#L24

**Comment by exch-bms2** [comment]
修正しました。次回リリースに反映されます。

本症状は、36進数で1000以上のBMP定義のファイルが存在せず、かつBGA/LAYERチャンネルで再生される場合に発生します。

なお、thanatos_6yk.pmsは別BGAバージョンのTHANATOSの差分ファイルです。
