### ISSUE TITLE
Songlist garbage is displayed when song select skin is changed

### ISSUE THREAD

**Issue by Shimi9999** [exch-bms2/beatoraja#559]
v0.8で、選曲スキンを変更すると、曲リストの下部に曲リストの"ごみ"が表示されることがあります。
![image](https://user-images.githubusercontent.com/38182044/93200603-f0757b00-f78a-11ea-9fc9-86948162c4dc.png)
![image](https://user-images.githubusercontent.com/38182044/93200626-fbc8a680-f78a-11ea-90fa-0d40c3d35345.png)

再現方法
1. 選曲画面からスキンセレクトに行く
2. 選曲スキンを変更する
3. 選曲画面に戻ると"ごみ"が表示されることがある

beatoraja defaultとModernChicSelect-1.3.1の切り替えで再現しましたが、他にもm-selectやBrook v1.0.1でも再現しました。

また、"ごみ"が表示された状態で任意のフォルダを開くと、以下のエラーが発生してbeatorajaが落ちることがあります。
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:294)
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:82)
        at bms.player.beatoraja.skin.SkinTextFont.setLayout(Unknown Source)
        at bms.player.beatoraja.skin.SkinTextFont.draw(Unknown Source)
        at bms.player.beatoraja.select.BarRenderer.render(Unknown Source)
        at bms.player.beatoraja.select.SkinBar.draw(Unknown Source)
        at bms.player.beatoraja.skin.Skin.drawAllObjects(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
```

**Comment by wcko87** [comment]
This bug also happens in old versions of beatoraja.

These screenshots were taken in January 2019, on the Brook skin.

![image](https://user-images.githubusercontent.com/27341392/94331335-8cfb1100-0006-11eb-92e1-8bcb1feca99d.png)

![image](https://user-images.githubusercontent.com/27341392/94331339-9be1c380-0006-11eb-8953-f29437aba801.png)

**Comment by marysiamzawka** [comment]
This happens if the current Select skin's Songlist has less bars than the previous skin had.
The garbage shown are all the entries that have been truncated between skin changes.


Attached is a video showing the issue in action. 
Using m-select, I'm reproducing the issue by changing how many bars are drawn in the Songlist.
https://user-images.githubusercontent.com/20336327/184565633-d1a0bf85-11f7-4c67-a670-5fa256249ed3.mp4
