### ISSUE TITLE
[0.8.3] NullPointerException in music select.

### ISSUE THREAD

**Issue by mak1non** [exch-bms2/beatoraja#638]
Music select crash when opened specific folder.
Probably related #534 (Font issue?).

- Windows 10 64bit
- [Liberica JDK](https://bell-sw.com/pages/downloads/#/java-16-current) 16.0.2 (Full JDK)
- beatoraja 0.8.3 (Mocha-Repository)
- [DarkTheme](https://github.com/Shimi9999/DarkTheme)@42c64a251b1cc9e2f3e4855794ea29096f53ae1f

Note: I launched beatoraja with UTF-8. `-Dfile.encoding="UTF-8"`

```
Active code page: 65001

C:\Users\m\beatoraja>set _JAVA_OPTIONS=-Dsun.java2d.opengl=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dfile.encoding="UTF-8"

C:\Users\m\beatoraja>pushd C:\Users\m\beatoraja\

C:\Users\m\beatoraja>java -Xms1g -Xmx4g -jar beatoraja.jar
Picked up _JAVA_OPTIONS: -Dsun.java2d.opengl=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dfile.encoding="UTF-8"
8月 14, 2021 6:20:24 午後 bms.player.beatoraja.launcher.PlayConfigurationView initialize
情報: 初期化時間(ms) : 2
---- JPortAudio version 1246720, PortAudio V19.6.0-devel, revision unknown
8月 14, 2021 6:20:34 午後 bms.player.beatoraja.MainController$SystemSoundManager <init>
情報: 検出されたBGM Set : 1 Sound Set : 1
[Controllers] added manager for application, 1 managers active
8月 14, 2021 6:20:38 午後 bms.player.beatoraja.MainController$SystemSoundManager shuffle
情報: BGM Set : C:\Users\m\beatoraja\bgm\LR2 ver sta Sound Set : C:\Users\m\beatoraja\sound\lr2
8月 14, 2021 6:20:38 午後 bms.player.beatoraja.external.BMSSearchAccessor read
重大: BMS Search更新中の例外:Error parsing JSON on line 2 near: IC "-//IETF//DTD HTML 2.0//EN">
*ERROR*<html><head>
<title>301 Moved Permanently</title>
</head><body>

8月 14, 2021 6:20:38 午後 bms.player.beatoraja.skin.Skin prepare
情報: 描画されないことが確定しているSkinObject削除 : 1 / 248
8月 14, 2021 6:20:38 午後 bms.player.beatoraja.MainController create
情報: 初期化時間(ms) : 3476
Exception in thread "LWJGL Application" java.lang.NullPointerException: Cannot read field "y" because "run" is null
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:294)
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:82)
        at bms.player.beatoraja.skin.SkinTextFont.setLayout(Unknown Source)
        at bms.player.beatoraja.skin.SkinTextFont.draw(Unknown Source)
        at bms.player.beatoraja.select.BarRenderer.render(Unknown Source)
        at bms.player.beatoraja.select.SkinBar.draw(Unknown Source)
        at bms.player.beatoraja.skin.Skin.drawAllObjects(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
```

**Comment by mak1non** [comment]
Video:

https://user-images.githubusercontent.com/48780047/129441663-b9295a49-b87e-4350-8481-acd762c7d2ab.mp4

**Comment by Shimi9999** [comment]
★13 黯 / 紅蓮月影 の`黯`の字を曲リストに[Koruri](https://github.com/Koruri/Koruri)フォントで表示しようとする時にNPEになるようです。
mocha版ビルド0.8.3では再現しましたが、開発環境からビルドした本体では再現しませんでした。

**Comment by mak1non** [comment]
masterブランチ `ea8879ce0df7e53fa9d5c2bc575323617cbaaa01` をビルドして検証してみたところ、該当する不具合が再現しないことを確認しました。このissueはcloseしてしまって構いません。

少し気になった点として、0.8.3 (mocha版) では `㌍㌢` などを表示する際にコンソールに例外が出力されていた (当該文字は空白になっています) のに対し、master版ではその例外も出力されなくなっていたというものがあります。
```
8月 15, 2021 9:39:35 午後 bms.player.beatoraja.skin.SkinTextFont prepareText
警告: Font準備失敗 : ㌍㌢ - Unable to create a font with no texture regions.
```
表に見える動作に変わりは無いので特に問題はなさそうですが、この修正が意図したものか判断できないので、念のため報告しておきます。開発/確認ありがとうございます。

**Comment by Shimi9999** [comment]
開発環境のLibGDXとgdx-freetype関連のjarファイル群を[nightly build](https://libgdx.badlogicgames.com/ci/nightlies/libgdx-nightly-20210226.zip)のものに置き換えたところ、`㌍㌢`と`黯`を検出して例外を出力するようになりました。
```
8月 15, 2021 11:02:35 午後 bms.player.beatoraja.skin.SkinTextFont prepareText
警告: Font準備失敗 : ㌍㌢ - Unable to create a font with no texture regions.
8月 15, 2021 11:02:48 午後 bms.player.beatoraja.skin.SkinTextFont prepareText
警告: Font準備失敗 : 黯 - Unable to create a font with no texture regions.
```

置き換えたファイル
- gdx.jar
- gdx-backend-lwjgl.jar
- gdx-backend-lwjgl-natives.jar
- gdx-freetype.jar
- gdx-freetype-natives.jar
- gdx-natives.jar

このことから、libGDX関連のjarファイル群を最新版に更新することで、この問題が解消する可能性があります。

また、mocha版と開発環境ビルドの動作が異なるので、GitHub上のbeatorajaプロジェクト内のLibGDX関連jar群のバージョンと、mocha版をビルドする際に使用されているjar群のバージョンが異なっていることも考えられます。
