### ISSUE TITLE
[music select] problem when change rival in the opposite direction

### ISSUE THREAD

**Issue by N-ISOGE** [exch-bms2/beatoraja#671]
歌の選択中、ライバルを選択しない状態で逆方向に行く時問題です。

Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 2
        at bms.player.beatoraja.skin.property.EventFactory$EventType.lambda$static$21(Unknown Source)
        at bms.player.beatoraja.skin.property.EventFactory$2.exec(Unknown Source)
        at bms.player.beatoraja.skin.property.Event.exec(Unknown Source)
        at bms.player.beatoraja.skin.SkinObject.mousePressed(Unknown Source)
        at bms.player.beatoraja.skin.Skin.mousePressed(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

https://user-images.githubusercontent.com/7279031/147108392-7b5a2516-81e0-413d-845e-85b5ff521d37.mp4

**Comment by Chazoshtare** [comment]
I fixed this in a PR, choosing a previous rival while none was picked led to OutOfBoundsException.
