### ISSUE TITLE
NullPointerException on openJDK when loading a song 

### ISSUE THREAD

**Issue by lukeoftheaura** [exch-bms2/beatoraja#68]
Whenever I try to load a song in beatoraja instead of loading correctly it fades to a white screen, then throws this error, after which I have to kill the process:
'''
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at bms.player.beatoraja.play.BMSPlayer.create(Unknown Source)
	at bms.player.beatoraja.MainController.changeState(Unknown Source)
	at bms.player.beatoraja.decide.MusicDecide.render(Unknown Source)
	at bms.player.beatoraja.MainController.render(Unknown Source)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
'''
OS: arch linux 64bit

**Comment by excln** [comment]
Does it happen only on 0.4.3 and are you using only a mouse or arrow keys to select a song?

If so, please try selecting songs with the keys that you use to play songs. (For example, press 'Z' key to decide if you play with the keyboard in the default key configuration.) If it goes well, the exception is a bug that we already recognized and fixed in the master branch.

**Comment by lukeoftheaura** [comment]
ah, that seems to fix it.
